-- ============================================
-- InciLog テストデータ（汎用インフラ監視）
-- 会社固有情報を含まない汎用データ
-- ============================================

-- ホストマスタ
INSERT INTO hosts (hostname, description, category) VALUES
  ('WEB-PROD-01',  '本番Webサーバ1 (nginx)',          'Web'),
  ('WEB-PROD-02',  '本番Webサーバ2 (nginx)',          'Web'),
  ('AP-PROD-01',   '本番APサーバ1 (Tomcat)',          'AP'),
  ('AP-PROD-02',   '本番APサーバ2 (Tomcat)',          'AP'),
  ('DB-PROD-01',   '本番DBサーバ (PostgreSQL Primary)','DB'),
  ('DB-PROD-02',   '本番DBサーバ (PostgreSQL Replica)','DB'),
  ('BATCH-01',     'バッチ処理サーバ',                  'Batch'),
  ('MON-01',       '統合監視サーバ (Zabbix)',          '監視'),
  ('NW-CORE-01',   'コアスイッチ (Catalyst)',           'NW'),
  ('NW-DIST-01',   'ディストリビューションSW',          'NW'),
  ('FW-01',        'ファイアウォール (FortiGate)',      'NW'),
  ('LB-01',        'ロードバランサ (F5 BIG-IP)',       'NW'),
  ('MAIL-01',      'メールサーバ (Postfix)',           'Mail'),
  ('FILE-01',      'ファイルサーバ (Samba)',            'Storage'),
  ('BK-01',        'バックアップサーバ (Veeam)',        'Backup'),
  ('VM-HOST-01',   '仮想基盤ホスト1 (ESXi)',           'VM'),
  ('VM-HOST-02',   '仮想基盤ホスト2 (ESXi)',           'VM'),
  ('DNS-01',       'DNSサーバ (BIND)',                 'Infra'),
  ('NTP-01',       'NTPサーバ',                        'Infra'),
  ('PROXY-01',     'プロキシサーバ (Squid)',            'Infra');

-- 対応テンプレート
INSERT INTO response_templates (title, content, team, match_keyword) VALUES
  ('ディスク使用率アラート',       E'ディスク使用率が閾値を超過。\n不要ファイルの削除またはディスク拡張を検討。',         '運用T', 'disk_usage'),
  ('CPU高負荷',                   E'CPU使用率が閾値を超過。\nプロセス確認(top/htop)で原因特定。負荷が継続する場合はスケールアップを検討。', '運用T', 'cpu_high'),
  ('メモリ不足',                  E'メモリ使用率が閾値を超過。\nOOM Killerが動作する前にプロセスの再起動またはメモリ増設を検討。',       '運用T', 'memory_high'),
  ('NW linkDown',                 E'ポートのリンクダウンを検知。\n対向機器の状態とケーブルを確認。計画作業による場合は静観。',           '運用T', 'linkDown'),
  ('NW linkUp',                   'ポートのリンクアップを確認。linkDown復旧。正常動作を確認し完了。',                                   '運用T', 'linkUp'),
  ('サービス停止',                E'サービスの停止を検知。\nsystemctl status で状態確認 → restart で復旧試行。',                       '運用T', 'service_down'),
  ('SSL証明書期限',               E'SSL証明書の有効期限が近づいています。\n更新手順に従い証明書を更新してください。',                    '運用T', 'ssl_expire'),
  ('バックアップ失敗',            E'バックアップジョブが失敗しました。\nログを確認し、ディスク容量・ネットワーク接続を確認してください。', '運用T', 'backup_fail'),
  ('ログイン失敗',                '認証失敗を検知。正規ユーザの入力ミスか不正アクセスか確認。連続発生時はアカウントロック状況を確認。',  'セキュリティT', 'auth_fail'),
  ('VMware HA イベント',          E'仮想マシンのHA再起動を検知。\nホストの障害状況を確認。vCLSの再起動であれば静観。',                  '運用T', 'vm_ha');

INSERT INTO response_templates (title, content, team, match_code) VALUES
  ('Zabbixトリガー復旧',          '監視トリガーが自動復旧しました。一時的な負荷による発報と判断し静観。',                              '運用T', 'RESOLVED'),
  ('バッチジョブ異常終了',        E'バッチジョブが異常終了しました。\nジョブログを確認し、リカバリ手順に従い再実行してください。',        '開発T',     'JOB_FAIL');

-- ============================================
-- ログデータ 100件
-- ============================================

-- === ディスク系アラート (10件) ===
INSERT INTO logs (event_date, event_time, host_id, message, team, response, assignee, reviewer, status, event_keyword) VALUES
('2026-03-01','09:15:22',(SELECT id FROM hosts WHERE hostname='WEB-PROD-01'),
  'WARNING: Disk usage on /var/log reached 92%. Threshold: 90%',
  '運用T','不要ログファイルを削除し85%に低下。logrotate設定を見直し。','山田','鈴木','closed','disk_usage'),
('2026-03-05','14:30:11',(SELECT id FROM hosts WHERE hostname='DB-PROD-01'),
  'CRITICAL: Disk usage on /var/lib/postgresql reached 95%. Threshold: 90%',
  '運用T','古いWALファイルをアーカイブ後削除。pg_repackでテーブル圧縮実施。','佐藤','山田','closed','disk_usage'),
('2026-03-08','03:22:45',(SELECT id FROM hosts WHERE hostname='BATCH-01'),
  'WARNING: Disk usage on /data/export reached 88%. Threshold: 85%',
  '運用T','エクスポート済みファイルをアーカイブストレージに移動。','田中','佐藤','closed','disk_usage'),
('2026-03-12','11:05:33',(SELECT id FROM hosts WHERE hostname='FILE-01'),
  'CRITICAL: Disk usage on /share reached 97%. Threshold: 90%',
  '運用T','各部門に不要ファイル削除を依頼。一時的に500GB追加割当。','山田','鈴木','closed','disk_usage'),
('2026-03-15','22:10:08',(SELECT id FROM hosts WHERE hostname='BK-01'),
  'WARNING: Disk usage on /backup reached 91%. Threshold: 90%',
  '運用T','30日以上前のバックアップを外部ストレージに退避。','佐藤','田中','closed','disk_usage'),
('2026-03-20','07:45:19',(SELECT id FROM hosts WHERE hostname='MAIL-01'),
  'WARNING: Disk usage on /var/spool/mail reached 89%. Threshold: 85%',
  '運用T','長期未読メールボックスをアーカイブ。メールボックスサイズ制限を設定。','田中','山田','closed','disk_usage'),
('2026-03-25','16:30:55',(SELECT id FROM hosts WHERE hostname='WEB-PROD-02'),
  'WARNING: Disk usage on /var/log reached 87%. Threshold: 85%',
  '運用T','アクセスログのローテーション周期を7日→3日に短縮。','鈴木','佐藤','closed','disk_usage'),
('2026-04-01','08:20:14',(SELECT id FROM hosts WHERE hostname='AP-PROD-01'),
  'WARNING: Disk usage on /opt/tomcat/logs reached 91%. Threshold: 90%',
  '運用T',NULL,'山田',NULL,'new','disk_usage'),
('2026-04-05','10:15:30',(SELECT id FROM hosts WHERE hostname='DB-PROD-02'),
  'WARNING: Disk usage on /var/lib/postgresql reached 88%. Threshold: 85%',
  '運用T','レプリケーション遅延なし。Primaryと同様にWALクリーンアップ実施。','佐藤','鈴木','responded','disk_usage'),
('2026-04-10','15:45:22',(SELECT id FROM hosts WHERE hostname='MON-01'),
  'WARNING: Disk usage on /var/lib/zabbix reached 93%. Threshold: 90%',
  '運用T',NULL,NULL,NULL,'new','disk_usage');

-- === CPU/メモリ系アラート (12件) ===
INSERT INTO logs (event_date, event_time, host_id, message, team, response, assignee, reviewer, status, event_keyword) VALUES
('2026-03-02','10:30:45',(SELECT id FROM hosts WHERE hostname='AP-PROD-01'),
  'CRITICAL: CPU usage reached 98% for 5 minutes. Top process: java (PID 12345)',
  '運用T','Tomcatのスレッドプール枯渇。maxThreads=200→300に変更し再起動。','山田','鈴木','closed','cpu_high'),
('2026-03-06','13:22:18',(SELECT id FROM hosts WHERE hostname='AP-PROD-02'),
  'WARNING: CPU usage reached 85% for 10 minutes. Top process: java (PID 23456)',
  '運用T','GCログ確認。Full GC多発のためヒープサイズを4G→6Gに変更。','佐藤','山田','closed','cpu_high'),
('2026-03-10','02:15:33',(SELECT id FROM hosts WHERE hostname='DB-PROD-01'),
  'CRITICAL: CPU usage reached 95% for 3 minutes. Top process: postgres (PID 34567)',
  '運用T','pg_stat_activityで長時間クエリ発見。EXPLAIN結果からインデックス追加で解決。','佐藤','鈴木','closed','cpu_high'),
('2026-03-14','09:45:12',(SELECT id FROM hosts WHERE hostname='BATCH-01'),
  'WARNING: CPU usage reached 90% for 15 minutes. Top process: python3 (PID 45678)',
  '運用T','月次集計バッチの実行時間帯と重複。バッチスケジュールを調整。','田中','山田','closed','cpu_high'),
('2026-03-18','16:10:27',(SELECT id FROM hosts WHERE hostname='WEB-PROD-01'),
  'WARNING: Memory usage reached 92%. Available: 800MB / 8192MB',
  '運用T','nginxワーカープロセス数を調整。worker_connections設定を最適化。','鈴木','佐藤','closed','memory_high'),
('2026-03-22','11:30:44',(SELECT id FROM hosts WHERE hostname='AP-PROD-01'),
  'CRITICAL: Memory usage reached 96%. OOM Killer may activate. Available: 512MB / 16384MB',
  '運用T','Javaヒープダンプ取得。メモリリーク箇所を特定しアプリチームに報告。暫定でTomcat再起動。','山田','鈴木','closed','memory_high'),
('2026-03-26','08:55:31',(SELECT id FROM hosts WHERE hostname='DB-PROD-01'),
  'WARNING: Memory usage reached 88%. shared_buffers consuming 4GB',
  '運用T','shared_buffersの設定値が適正範囲内であることを確認。一時的なキャッシュ増加のため静観。','佐藤','山田','closed','memory_high'),
('2026-03-30','20:15:09',(SELECT id FROM hosts WHERE hostname='PROXY-01'),
  'WARNING: CPU usage reached 87% for 5 minutes. Top process: squid (PID 56789)',
  '運用T','キャッシュヒット率低下が原因。cache_dir設定を見直し。','田中','鈴木','closed','cpu_high'),
('2026-04-02','14:20:38',(SELECT id FROM hosts WHERE hostname='WEB-PROD-02'),
  'WARNING: Memory usage reached 90%. Available: 1024MB / 8192MB',
  '運用T','接続数増加に伴う一時的な上昇。30分後に自然回復。','鈴木','山田','closed','memory_high'),
('2026-04-06','09:30:15',(SELECT id FROM hosts WHERE hostname='AP-PROD-02'),
  'CRITICAL: CPU usage reached 99% for 2 minutes. Top process: java (PID 67890)',
  '運用T',NULL,'山田',NULL,'new','cpu_high'),
('2026-04-08','11:45:22',(SELECT id FROM hosts WHERE hostname='MAIL-01'),
  'WARNING: Memory usage reached 85%. postfix queue growing',
  '運用T','メールキュー滞留。スパムフィルタの一時的な負荷増。キュー処理後に正常化。','田中','佐藤','responded','memory_high'),
('2026-04-12','03:10:55',(SELECT id FROM hosts WHERE hostname='MON-01'),
  'WARNING: CPU usage reached 88% for 10 minutes. Zabbix server process',
  '運用T',NULL,NULL,NULL,'new','cpu_high');

-- === NWアラート (15件) ===
INSERT INTO logs (event_date, event_time, host_id, message, team, response, assignee, reviewer, status, source_device, interface_no, event_keyword) VALUES
('2026-03-01','14:22:10',(SELECT id FROM hosts WHERE hostname='NW-CORE-01'),
  'SNMP Trap: Interface GigabitEthernet0/1 link down (ifIndex: 10101)',
  '運用T','対向サーバWEB-PROD-01のNIC再起動による一時的な切断。5秒後にlinkUp確認。','鈴木','山田','closed','NW-CORE-01','10101','linkDown'),
('2026-03-01','14:22:15',(SELECT id FROM hosts WHERE hostname='NW-CORE-01'),
  'SNMP Trap: Interface GigabitEthernet0/1 link up (ifIndex: 10101)',
  '運用T','linkDown復旧確認。通信影響なし。','鈴木','山田','closed','NW-CORE-01','10101','linkUp'),
('2026-03-07','22:30:45',(SELECT id FROM hosts WHERE hostname='NW-DIST-01'),
  'SNMP Trap: Interface GigabitEthernet1/0/24 link down (ifIndex: 10124)',
  '運用T','夜間メンテナンス作業によるもの。計画作業のため静観。','田中','鈴木','closed','NW-DIST-01','10124','linkDown'),
('2026-03-07','23:45:12',(SELECT id FROM hosts WHERE hostname='NW-DIST-01'),
  'SNMP Trap: Interface GigabitEthernet1/0/24 link up (ifIndex: 10124)',
  '運用T','メンテナンス完了。linkUp確認。','田中','鈴木','closed','NW-DIST-01','10124','linkUp'),
('2026-03-11','08:15:33',(SELECT id FROM hosts WHERE hostname='FW-01'),
  'SNMP Trap: Interface port10 link down (ifIndex: 10)',
  '運用T','DMZセグメントのサーバ停止作業に伴うlinkDown。予定作業。','鈴木','佐藤','closed','FW-01','10','linkDown'),
('2026-03-11','10:30:22',(SELECT id FROM hosts WHERE hostname='FW-01'),
  'SNMP Trap: Interface port10 link up (ifIndex: 10)',
  '運用T','DMZサーバ起動完了。通信復旧確認。','鈴木','佐藤','closed','FW-01','10','linkUp'),
('2026-03-16','03:45:08',(SELECT id FROM hosts WHERE hostname='NW-CORE-01'),
  'SNMP Trap: Interface TenGigabitEthernet1/1 link down (ifIndex: 20101)',
  '運用T','10G上位回線の瞬断。ISP側の機器交換作業によるもの。事前連絡あり。','山田','鈴木','closed','NW-CORE-01','20101','linkDown'),
('2026-03-16','03:45:35',(SELECT id FROM hosts WHERE hostname='NW-CORE-01'),
  'SNMP Trap: Interface TenGigabitEthernet1/1 link up (ifIndex: 20101)',
  '運用T','上位回線復旧。パケットロスなし確認。','山田','鈴木','closed','NW-CORE-01','20101','linkUp'),
('2026-03-21','15:20:19',(SELECT id FROM hosts WHERE hostname='LB-01'),
  'Pool member WEB-PROD-01:443 status changed to DOWN. Health check failed.',
  '運用T','WEB-PROD-01のnginx再起動中に一時的にヘルスチェック失敗。再起動完了後にUP復帰。','鈴木','田中','closed','LB-01',NULL,'service_down'),
('2026-03-21','15:22:45',(SELECT id FROM hosts WHERE hostname='LB-01'),
  'Pool member WEB-PROD-01:443 status changed to UP. Health check passed.',
  '運用T','ヘルスチェック復旧確認。','鈴木','田中','closed','LB-01',NULL,'linkUp'),
('2026-03-28','19:10:33',(SELECT id FROM hosts WHERE hostname='NW-CORE-01'),
  'SNMP Trap: Interface GigabitEthernet0/5 link down (ifIndex: 10105)',
  '運用T','FILE-01のNICフラッピング。ケーブル交換で解消。','山田','佐藤','closed','NW-CORE-01','10105','linkDown'),
('2026-03-28','19:15:22',(SELECT id FROM hosts WHERE hostname='NW-CORE-01'),
  'SNMP Trap: Interface GigabitEthernet0/5 link up (ifIndex: 10105)',
  '運用T','ケーブル交換後linkUp安定。','山田','佐藤','closed','NW-CORE-01','10105','linkUp'),
('2026-04-03','07:05:11',(SELECT id FROM hosts WHERE hostname='NW-DIST-01'),
  'SNMP Trap: Interface GigabitEthernet1/0/12 link down (ifIndex: 10112)',
  '運用T',NULL,'鈴木',NULL,'new','NW-DIST-01','10112','linkDown'),
('2026-04-07','21:30:44',(SELECT id FROM hosts WHERE hostname='FW-01'),
  'SNMP Trap: Interface port3 link down (ifIndex: 3)',
  '運用T','内部セグメント側ポート。対向SW再起動による瞬断。すぐ復旧。','鈴木','山田','responded','FW-01','3','linkDown'),
('2026-04-11','10:20:18',(SELECT id FROM hosts WHERE hostname='LB-01'),
  'Pool member AP-PROD-02:8080 status changed to DOWN. Health check failed.',
  '運用T',NULL,NULL,NULL,'new','LB-01',NULL,'service_down');

-- === サービス系アラート (12件) ===
INSERT INTO logs (event_date, event_time, host_id, message, team, response, assignee, reviewer, status, event_keyword) VALUES
('2026-03-03','06:30:12',(SELECT id FROM hosts WHERE hostname='WEB-PROD-01'),
  'Service nginx is not running. systemctl status: inactive (dead)',
  '運用T','OOM Killerによりnginxプロセスが停止。メモリ増設後にsystemctl restart nginxで復旧。','山田','鈴木','closed','service_down'),
('2026-03-09','12:45:33',(SELECT id FROM hosts WHERE hostname='AP-PROD-01'),
  'Service tomcat is not running. systemctl status: failed',
  '運用T','catalina.outにOutOfMemoryError確認。ヒープ設定見直し後に再起動。','佐藤','山田','closed','service_down'),
('2026-03-13','18:20:08',(SELECT id FROM hosts WHERE hostname='DB-PROD-02'),
  'Service postgresql is not running. systemctl status: inactive',
  '運用T','レプリケーション接続断によるPostgreSQL停止。primary側のpg_hba.conf確認後再起動。','佐藤','鈴木','closed','service_down'),
('2026-03-17','04:10:55',(SELECT id FROM hosts WHERE hostname='MAIL-01'),
  'Service postfix is not running. systemctl status: failed',
  '運用T','メールキュー破損。postsuper -dで不正キュー削除後にsystemctl restart postfix。','田中','山田','closed','service_down'),
('2026-03-23','09:15:22',(SELECT id FROM hosts WHERE hostname='DNS-01'),
  'Service named is not running. systemctl status: inactive (dead)',
  '運用T','ゾーンファイルのシンタックスエラー。named-checkzoneで修正後に再起動。','田中','鈴木','closed','service_down'),
('2026-03-27','15:40:18',(SELECT id FROM hosts WHERE hostname='PROXY-01'),
  'Service squid is not running. systemctl status: failed',
  '運用T','キャッシュディレクトリの権限変更が原因。chownで修正後に再起動。','鈴木','佐藤','closed','service_down'),
('2026-04-01','21:30:44',(SELECT id FROM hosts WHERE hostname='WEB-PROD-02'),
  'Service nginx is not running. systemctl status: inactive (dead)',
  '運用T','設定ファイル変更後のreload失敗。nginx -tでシンタックスエラー発見。修正後に再起動。','山田','田中','closed','service_down'),
('2026-04-04','07:22:11',(SELECT id FROM hosts WHERE hostname='NTP-01'),
  'Service ntpd is not running. systemctl status: inactive',
  '運用T','ntpd停止。上位NTPサーバへの到達性問題。ネットワーク復旧後にサービス再起動。','田中','鈴木','closed','service_down'),
('2026-04-09','13:55:30',(SELECT id FROM hosts WHERE hostname='AP-PROD-02'),
  'Service tomcat is not running. systemctl status: failed',
  '運用T',NULL,'佐藤',NULL,'new','service_down'),
('2026-04-10','16:45:22',(SELECT id FROM hosts WHERE hostname='WEB-PROD-01'),
  'WARNING: SSL certificate for www.example.com expires in 14 days',
  '運用T','証明書更新手続きを開始。Let''s Encryptで自動更新設定済みだが手動確認。','鈴木','山田','responded','ssl_expire'),
('2026-04-12','08:30:15',(SELECT id FROM hosts WHERE hostname='MAIL-01'),
  'WARNING: SSL certificate for mail.example.com expires in 7 days',
  '運用T',NULL,NULL,NULL,'new','ssl_expire'),
('2026-04-14','11:10:33',(SELECT id FROM hosts WHERE hostname='PROXY-01'),
  'Service squid is not running. systemctl status: failed. Reason: cache_dir permission denied',
  '運用T',NULL,NULL,NULL,'new','service_down');

-- === バッチジョブ系アラート (15件) ===
INSERT INTO logs (event_date, event_time, host_id, message, team, response, assignee, reviewer, status, message_code, event_keyword) VALUES
('2026-03-01','02:30:10',(SELECT id FROM hosts WHERE hostname='BATCH-01'),
  'JOB_FAIL: Daily backup job [daily_db_backup] failed. Exit code: 1. Error: Connection refused to DB-PROD-01:5432',
  '開発T','DBサーバのメンテナンスウィンドウと重複。スケジュール変更後に再実行し正常終了。','佐藤','山田','closed','JOB_FAIL','backup_fail'),
('2026-03-04','03:15:22',(SELECT id FROM hosts WHERE hostname='BATCH-01'),
  'JOB_FAIL: Monthly report generation [monthly_report] failed. Exit code: 2. Error: Out of memory',
  '開発T','レポート対象データ量増加によるメモリ不足。バッチサーバのメモリを16G→32Gに増設。','田中','佐藤','closed','JOB_FAIL',NULL),
('2026-03-08','01:05:44',(SELECT id FROM hosts WHERE hostname='BATCH-01'),
  'JOB_FAIL: Data export job [csv_export] failed. Exit code: 1. Error: Disk full on /data/export',
  '開発T','エクスポート先ディスク容量不足。古いファイル削除後に再実行。','田中','山田','closed','JOB_FAIL',NULL),
('2026-03-11','04:30:18',(SELECT id FROM hosts WHERE hostname='BATCH-01'),
  'JOB_FAIL: Daily ETL job [etl_daily] failed. Exit code: 3. Error: Source file not found: /data/input/daily_20260311.csv',
  '開発T','外部システムからのファイル連携遅延。連携先に確認後、ファイル到着を待って再実行。','佐藤','田中','closed','JOB_FAIL',NULL),
('2026-03-15','05:20:33',(SELECT id FROM hosts WHERE hostname='BATCH-01'),
  'JOB_FAIL: Weekly aggregation [weekly_agg] failed. Exit code: 1. Error: Deadlock detected in target table',
  '開発T','オンライン処理とのロック競合。バッチ実行時間を早朝3時→深夜1時に変更。','田中','佐藤','closed','JOB_FAIL',NULL),
('2026-03-19','02:45:11',(SELECT id FROM hosts WHERE hostname='BATCH-01'),
  'JOB_FAIL: Daily backup job [daily_db_backup] failed. Exit code: 1. Error: pg_dump timeout after 3600 seconds',
  '開発T','大量データ更新後のバックアップ時間超過。pg_dumpのタイムアウトを7200秒に延長。','佐藤','山田','closed','JOB_FAIL','backup_fail'),
('2026-03-22','06:10:27',(SELECT id FROM hosts WHERE hostname='BATCH-01'),
  'JOB_FAIL: Log rotation job [log_rotate] failed. Exit code: 1. Error: Permission denied on /var/log/app',
  '開発T','ログディレクトリの権限変更が原因。chown修正後に再実行。','山田','佐藤','closed','JOB_FAIL',NULL),
('2026-03-25','03:30:55',(SELECT id FROM hosts WHERE hostname='BATCH-01'),
  'RESOLVED: Daily backup job [daily_db_backup] completed successfully. Duration: 2h15m',
  '開発T','前回失敗分の正常完了確認。','佐藤','山田','closed','RESOLVED','backup_fail'),
('2026-03-29','01:55:44',(SELECT id FROM hosts WHERE hostname='BATCH-01'),
  'JOB_FAIL: Data sync job [master_sync] failed. Exit code: 2. Error: API endpoint returned 503',
  '開発T','連携先APIサーバのメンテナンス中。翌日再実行で正常終了。','田中','佐藤','closed','JOB_FAIL',NULL),
('2026-04-01','04:15:33',(SELECT id FROM hosts WHERE hostname='BATCH-01'),
  'JOB_FAIL: Monthly billing job [billing_calc] failed. Exit code: 1. Error: Invalid data in row 15234',
  '開発T','入力データの不整合。データ修正後に再実行。','田中','山田','closed','JOB_FAIL',NULL),
('2026-04-04','02:30:22',(SELECT id FROM hosts WHERE hostname='BATCH-01'),
  'JOB_FAIL: Daily backup job [daily_db_backup] failed. Exit code: 1. Error: Connection refused to DB-PROD-01:5432',
  '開発T',NULL,'佐藤',NULL,'new','JOB_FAIL','backup_fail'),
('2026-04-07','03:45:18',(SELECT id FROM hosts WHERE hostname='BATCH-01'),
  'JOB_FAIL: Daily ETL job [etl_daily] failed. Exit code: 3. Error: Source file not found: /data/input/daily_20260407.csv',
  '開発T','外部連携ファイル未着。連携先に問い合わせ中。','田中',NULL,'responded','JOB_FAIL',NULL),
('2026-04-09','05:10:11',(SELECT id FROM hosts WHERE hostname='BATCH-01'),
  'JOB_FAIL: Weekly aggregation [weekly_agg] failed. Exit code: 1. Error: Deadlock detected in target table',
  '開発T',NULL,NULL,NULL,'new','JOB_FAIL',NULL),
('2026-04-11','01:20:33',(SELECT id FROM hosts WHERE hostname='BK-01'),
  'JOB_FAIL: VM snapshot backup [vm_backup_daily] failed. Error: Insufficient disk space on backup volume',
  '運用T',NULL,'佐藤',NULL,'new','JOB_FAIL','backup_fail'),
('2026-04-13','02:55:44',(SELECT id FROM hosts WHERE hostname='BATCH-01'),
  'JOB_FAIL: Data export job [csv_export] failed. Exit code: 1. Error: Disk full on /data/export',
  '開発T',NULL,NULL,NULL,'new','JOB_FAIL',NULL);

-- === VMware / 仮想基盤アラート (10件) ===
INSERT INTO logs (event_date, event_time, host_id, message, team, response, assignee, reviewer, status, source_device, event_keyword) VALUES
('2026-03-02','19:30:22',(SELECT id FROM hosts WHERE hostname='VM-HOST-01'),
  'VMware vCenter: Virtual machine [vCLS-01] has been powered off (vmwVmPoweredOff)',
  '運用T','vCLS（vSphere Cluster Service）の自動再起動。正常動作のため静観。','山田','鈴木','closed','VM-HOST-01','vm_ha'),
('2026-03-02','19:30:45',(SELECT id FROM hosts WHERE hostname='VM-HOST-01'),
  'VMware vCenter: Virtual machine [vCLS-01] has been powered on (vmwVmPoweredOn)',
  '運用T','vCLS再起動完了。正常動作確認。','山田','鈴木','closed','VM-HOST-01','vm_ha'),
('2026-03-10','21:15:18',(SELECT id FROM hosts WHERE hostname='VM-HOST-02'),
  'VMware vCenter: Virtual machine [AP-PROD-02] heartbeat not detected (vmwVmHBLost)',
  '運用T','VMware Toolsの一時的な応答遅延。ゲストOS上では正常動作。VMware Tools再起動で解消。','佐藤','山田','closed','VM-HOST-02','vm_ha'),
('2026-03-10','21:18:33',(SELECT id FROM hosts WHERE hostname='VM-HOST-02'),
  'VMware vCenter: Virtual machine [AP-PROD-02] heartbeat detected (vmwVmHBDetected)',
  '運用T','ハートビート復旧確認。','佐藤','山田','closed','VM-HOST-02','vm_ha'),
('2026-03-18','03:05:44',(SELECT id FROM hosts WHERE hostname='VM-HOST-01'),
  'VMware vCenter: Host [VM-HOST-01] memory usage reached 92%. DRS may trigger vMotion.',
  '運用T','テスト環境VMの一時的なメモリ消費。テスト完了後に正常化。','山田','佐藤','closed','VM-HOST-01','memory_high'),
('2026-03-24','17:40:11',(SELECT id FROM hosts WHERE hostname='VM-HOST-02'),
  'VMware vCenter: Virtual machine [vCLS-02] has been powered off (vmwVmPoweredOff)',
  '運用T','vCLS自動再起動。静観。','鈴木','山田','closed','VM-HOST-02','vm_ha'),
('2026-03-24','17:40:38',(SELECT id FROM hosts WHERE hostname='VM-HOST-02'),
  'VMware vCenter: Virtual machine [vCLS-02] has been powered on (vmwVmPoweredOn)',
  '運用T','vCLS再起動完了。','鈴木','山田','closed','VM-HOST-02','vm_ha'),
('2026-04-02','22:10:15',(SELECT id FROM hosts WHERE hostname='VM-HOST-01'),
  'VMware vCenter: Virtual machine [DB-PROD-02] has been powered off unexpectedly (vmwVmPoweredOff)',
  '運用T','ESXiホストのハードウェア障害によるVM停止。HAにより別ホストで自動起動確認。','佐藤','鈴木','closed','VM-HOST-01','vm_ha'),
('2026-04-08','14:25:33',(SELECT id FROM hosts WHERE hostname='VM-HOST-01'),
  'VMware vCenter: Datastore [DS-PROD-01] usage reached 90%. Threshold: 85%',
  '運用T',NULL,'山田',NULL,'new','VM-HOST-01','disk_usage'),
('2026-04-13','04:30:22',(SELECT id FROM hosts WHERE hostname='VM-HOST-02'),
  'VMware vCenter: Virtual machine [WEB-PROD-01] heartbeat not detected (vmwVmHBLost)',
  '運用T',NULL,NULL,NULL,'new','VM-HOST-02','vm_ha');

-- === 認証/セキュリティアラート (12件) ===
INSERT INTO logs (event_date, event_time, host_id, message, team, response, assignee, reviewer, status, event_keyword) VALUES
('2026-03-03','11:22:33',(SELECT id FROM hosts WHERE hostname='WEB-PROD-01'),
  'sshd: Failed password for admin from 192.168.1.100 port 52341 ssh2',
  'セキュリティT','正規運用者のパスワード入力ミス。本人確認済み。','鈴木','山田','closed','auth_fail'),
('2026-03-03','11:22:35',(SELECT id FROM hosts WHERE hostname='WEB-PROD-01'),
  'sshd: Failed password for admin from 192.168.1.100 port 52341 ssh2',
  'セキュリティT','同上。2回目の入力ミス。','鈴木','山田','closed','auth_fail'),
('2026-03-03','11:22:40',(SELECT id FROM hosts WHERE hostname='WEB-PROD-01'),
  'sshd: Accepted password for admin from 192.168.1.100 port 52342 ssh2',
  'セキュリティT','3回目で認証成功。正常ログイン。','鈴木','山田','closed',NULL),
('2026-03-08','08:15:22',(SELECT id FROM hosts WHERE hostname='DB-PROD-01'),
  'PostgreSQL: FATAL: password authentication failed for user "app_user"',
  'セキュリティT','アプリケーション設定ファイルのパスワード不一致。設定修正で解消。','佐藤','鈴木','closed','auth_fail'),
('2026-03-14','23:45:11',(SELECT id FROM hosts WHERE hostname='FW-01'),
  'FortiGate: Intrusion detected. Signature: HTTP.URI.SQL.Injection. Source: 203.0.113.50 Action: Blocked',
  'セキュリティT','WAF/IPSによる自動ブロック。送信元IPを調査しブラックリストに追加。','鈴木','佐藤','closed',NULL),
('2026-03-19','16:30:44',(SELECT id FROM hosts WHERE hostname='FW-01'),
  'FortiGate: Brute force attack detected. Source: 198.51.100.25 Target: 443/tcp Attempts: 150',
  'セキュリティT','外部からのブルートフォース攻撃。送信元IPをブロック。fail2banの閾値を調整。','鈴木','山田','closed','auth_fail'),
('2026-03-24','09:10:18',(SELECT id FROM hosts WHERE hostname='AP-PROD-01'),
  'sshd: Failed password for root from 10.0.0.50 port 43210 ssh2. 5 consecutive failures.',
  'セキュリティT','内部サーバからのrootログイン試行。運用者の作業ミス。root SSHログイン禁止設定を再確認。','山田','鈴木','closed','auth_fail'),
('2026-03-30','14:55:33',(SELECT id FROM hosts WHERE hostname='MAIL-01'),
  'postfix/smtpd: warning: unknown[203.0.113.100]: SASL LOGIN authentication failed',
  'セキュリティT','外部からのSMTPリレー試行。SMTPリレー制限が正常に機能していることを確認。','田中','鈴木','closed','auth_fail'),
('2026-04-03','10:20:44',(SELECT id FROM hosts WHERE hostname='DB-PROD-01'),
  'PostgreSQL: FATAL: too many connections for role "app_user"',
  '運用T','コネクションプール設定不備。pgbouncerの最大接続数を調整。','佐藤','山田','closed',NULL),
('2026-04-06','22:15:11',(SELECT id FROM hosts WHERE hostname='FW-01'),
  'FortiGate: Brute force attack detected. Source: 192.0.2.80 Target: 22/tcp Attempts: 200',
  'セキュリティT',NULL,'鈴木',NULL,'new','auth_fail'),
('2026-04-10','07:45:22',(SELECT id FROM hosts WHERE hostname='WEB-PROD-02'),
  'sshd: Failed password for deploy from 10.0.0.30 port 55123 ssh2. Account locked after 5 failures.',
  'セキュリティT','デプロイ用アカウントのパスワード有効期限切れ。パスワード更新とロック解除を実施。','山田','鈴木','responded','auth_fail'),
('2026-04-14','03:30:55',(SELECT id FROM hosts WHERE hostname='AP-PROD-02'),
  'sshd: Failed password for invalid user test from 198.51.100.99 port 61234 ssh2',
  'セキュリティT',NULL,NULL,NULL,'new','auth_fail');

-- === バックアップ系 (6件) ===
INSERT INTO logs (event_date, event_time, host_id, message, team, response, assignee, reviewer, status, event_keyword) VALUES
('2026-03-05','05:30:22',(SELECT id FROM hosts WHERE hostname='BK-01'),
  'Veeam: Backup job [VM-Daily-Backup] completed with warnings. 2 VMs skipped due to snapshot consolidation needed.',
  '運用T','スナップショット統合が必要なVMを特定。手動で統合実施後、翌日のバックアップで正常完了。','佐藤','山田','closed','backup_fail'),
('2026-03-12','04:45:18',(SELECT id FROM hosts WHERE hostname='BK-01'),
  'Veeam: Backup job [DB-Full-Backup] failed. Error: Insufficient free disk space on backup repository.',
  '運用T','バックアップリポジトリの容量不足。古い世代のバックアップを削除し再実行。','佐藤','鈴木','closed','backup_fail'),
('2026-03-19','05:15:33',(SELECT id FROM hosts WHERE hostname='BK-01'),
  'Veeam: Backup job [VM-Daily-Backup] completed successfully. Duration: 3h45m. Size: 1.2TB',
  '運用T','正常完了確認。','佐藤','山田','closed',NULL),
('2026-03-26','06:00:44',(SELECT id FROM hosts WHERE hostname='BK-01'),
  'Veeam: Backup job [File-Server-Backup] failed. Error: Network path not found \\FILE-01\share',
  '運用T','ファイルサーバのSambaサービス再起動でネットワークパス復旧。バックアップ再実行で正常終了。','佐藤','田中','closed','backup_fail'),
('2026-04-02','05:30:11',(SELECT id FROM hosts WHERE hostname='BK-01'),
  'Veeam: Backup job [VM-Daily-Backup] failed. Error: Cannot create snapshot for VM [DB-PROD-01].',
  '運用T',NULL,'佐藤',NULL,'new','backup_fail'),
('2026-04-09','04:15:22',(SELECT id FROM hosts WHERE hostname='BK-01'),
  'Veeam: Backup job [DB-Full-Backup] completed with errors. 1 database backup truncated.',
  '運用T',NULL,NULL,NULL,'new','backup_fail');

-- === DNS/インフラ基盤系 (8件) ===
INSERT INTO logs (event_date, event_time, host_id, message, team, response, assignee, reviewer, status, event_keyword) VALUES
('2026-03-04','13:20:22',(SELECT id FROM hosts WHERE hostname='DNS-01'),
  'named: zone example.com/IN: refresh: could not set file modification time: Permission denied',
  '運用T','SELinux設定変更後の権限不整合。restoreconで修正。','田中','鈴木','closed',NULL),
('2026-03-09','07:45:33',(SELECT id FROM hosts WHERE hostname='NTP-01'),
  'ntpd: no servers reachable. Clock may drift.',
  '運用T','上位NTPサーバ(ntp.nict.jp)への到達性問題。ファイアウォールルール確認し復旧。','田中','山田','closed',NULL),
('2026-03-15','10:10:44',(SELECT id FROM hosts WHERE hostname='DNS-01'),
  'named: client 10.0.0.0/24: query (cache) denied for zone "internal.example.com"',
  '運用T','ACL設定漏れ。allow-queryに内部ネットワークを追加。','田中','鈴木','closed',NULL),
('2026-03-20','22:30:18',(SELECT id FROM hosts WHERE hostname='MON-01'),
  'Zabbix: Trigger fired: "Zabbix server performance is low" (Value: 45% busy)',
  '運用T','監視対象ホスト数増加に伴うZabbixサーバ負荷増。ハウスキーパー設定を最適化。','山田','佐藤','closed',NULL),
('2026-03-27','08:55:11',(SELECT id FROM hosts WHERE hostname='MON-01'),
  'Zabbix: More than 100 items having missing data for more than 10 minutes',
  '運用T','一時的なネットワーク輻輳によるデータ取得遅延。自然回復。','山田','田中','closed',NULL),
('2026-04-05','14:30:22',(SELECT id FROM hosts WHERE hostname='DNS-01'),
  'named: zone internal.example.com/IN: serial number (2026040401) unchanged. Zone may fail to transfer.',
  '運用T',NULL,'田中',NULL,'responded',NULL),
('2026-04-08','19:20:33',(SELECT id FROM hosts WHERE hostname='NTP-01'),
  'ntpd: clock step detected: offset 128.500 seconds. Possible clock issue.',
  '運用T',NULL,'田中',NULL,'new',NULL),
('2026-04-14','06:45:44',(SELECT id FROM hosts WHERE hostname='MON-01'),
  'Zabbix: Trigger fired: "Zabbix agent on WEB-PROD-01 is unreachable for 5 minutes"',
  '運用T',NULL,NULL,NULL,'new',NULL);
